require("comments")
require("keymaps")
require("lsp")
require("lualine").setup()
require("null_ls")
require("nvim-tree").setup()
require("options")
require("plugins")
require("treesitter")
require("gitsigns").setup()
require("doom_one").config()
-- require("rest")
require("telescope").load_extension "file_browser"
